# Generated by Django 4.2.7 on 2025-06-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='link',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='link_images/'),
        ),
    ]
